services:
  mock-cdn:
    build: .
    container_name: mock-cdn
    ports:
      - "${SRV_CDN_PORT}:${SRV_CDN_PORT}"
    volumes:
      - .:/app
      - ./.env:/app/.env
      - ./s3_inbox:/app/s3_inbox
      - ./s3_quarantine:/app/s3_quarantine
      - ./s3_longterm:/app/s3_longterm
    environment:
      - SRV_CDN_PORT=${SRV_CDN_PORT}
      - SRV_CDN_URL=${SRV_CDN_URL}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
    networks:
      - plant-db-mesh

networks:
  plant-db-mesh:
    name: plant-db-mesh
    external: true
